spring:
  datasource:
    url: jdbc:mysql://localhost:3306/petclinic?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Tmdwns0624@
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
